Add support for displaying PR labels
ONSdigital/fourth-wall pull request #2
Opened 2016-12-08 00:17 UTC by collisdigital

Fetches each PR as a GitHub issue (required to get the labels array) and displays any labels found on the wall in their GitHub chosen colour.

Example screenshot:

<img width="1273" alt="screen shot 2016-12-08 at 00 14 41" src="https://cloud.githubusercontent.com/assets/14041600/20992380/b1c4f554-bcdb-11e6-9ba5-cfd831b42d38.png">

2016-12-08 11:36 UTC, ajmaddaford requested changes

2016-12-08 11:36 UTC, ajmaddaford commented on javascript/core.js
> +  FourthWall.showLables = FourthWall.getQueryVariable('labels') === 'true';
Typo in showLables

2016-12-08 13:03 UTC, collisdigital commented on javascript/core.js
> +  FourthWall.showLables = FourthWall.getQueryVariable('labels') === 'true';
Done

2016-12-08 13:58 UTC, ajmaddaford approved these changes

2016-12-08 14:00 UTC, jonnyshaw89 approved these changes

2016-12-08 14:00 UTC, merged

2017-01-20 12:49 UTC, robyoung commented
Any plans to submit this upstream? Looks really useful.

2017-01-20 12:52 UTC, collisdigital commented
We're doing quite a few changes to fourth-wall locally at the moment and have broken (or not updated) the unit tests etc. When we finish the batch of changes and fix the tests we'll raise a PR. You can use this fork for now?

2017-01-20 12:52 UTC, collisdigital commented
See also https://github.com/ONSdigital/fourth-wall/pull/4

2017-01-20 12:53 UTC, collisdigital commented
Alternatively if you feel like fixing the Jasmine tests here and raising a PR we'd gladly accept :-D