Adding Feature to support PR Reviews
ONSdigital/fourth-wall pull request #5
Opened 2017-07-17 09:47 UTC by MIslam92

**What is the context of this PR?**

https://trello.com/c/2cE03AG1

**How to review**
Create own token in GitHub to access new additions to Forth Wall and enter:
file:///Users/"YourName"/projects/fourth-wall/index.html?"YOUR_TOKEN"&team=onsdigital/eq

**Who worked on the PR:**
Mohammad Samiul Islam
Shahi Noor Ahmed

2017-07-17 11:56 UTC, collisdigital commented
The `.idea` directory shouldn't be committed with this PR, if it's useful to have then it should be added as a separate PR

2017-07-17 12:00 UTC, shahi645 reviewed
Dont think all these xml files are required... CSS class needed for approval status

2017-07-17 12:01 UTC, collisdigital requested changes

2017-07-17 12:01 UTC, collisdigital commented on javascript/pull-view.js
> +      var baseSyncHTML2= "";
Is this still needed/used?

2017-07-17 12:01 UTC, collisdigital commented on javascript/pull-view.js
> +        '<div class="status-holder">', statusString , baseSyncHTML, approvalString, baseSyncHTML2, '</div>',
Is `baseSyncHTML2` needed? If so name needs re-thinking

2017-07-17 12:01 UTC, collisdigital commented on javascript/pull-view.js
> +                approved ++;
Some whitespace stuff here needs changing to match the style in the rest of the file

2017-07-17 12:01 UTC, collisdigital commented on javascript/pull-view.js
> +        classes = 'base-sync base-sync-rebase';
use unique classes for this status rather than re-using the sync ones

2017-07-17 12:05 UTC, MIslam92 commented
@collisdigital I have just added them to the .gitignore file and am gonna push that.

2017-07-17 12:09 UTC, MIslam92 commented on javascript/pull-view.js
> +      var baseSyncHTML2= "";
No it is redundant now in process of removing 👍

2017-07-18 10:42 UTC, MIslam92 commented on javascript/pull-view.js
> +                approved ++;
Done

2017-07-18 11:00 UTC, shahi645 approved these changes

2017-07-24 06:58 UTC, shahi645 approved these changes

2017-07-27 10:41 UTC, collisdigital requested changes

2017-07-27 10:41 UTC, collisdigital commented on fourth-wall.css
> +.needs-approval {
this is actually `.changes-requested`

2017-07-27 10:41 UTC, collisdigital commented on javascript/pull-view.js
> +                approved ++;
remove space before `++`

2017-07-27 10:41 UTC, collisdigital commented on javascript/pull-view.js
> +      else if (approved < 2 || requestedChanges > 0 || commented > 0 ){
if requestedChanges > 0 then it should be red. Consider putting that statement first e.g.

```
if (requestedChanges > 0) {
    classes = 'changes-requested';
}
else if (approved < 2) {
    classes = 'pending-approval';
}
else {
    classes = 'approved';
}
```

2017-07-27 11:54 UTC, MIslam92 commented on javascript/pull-view.js
> +      else if (approved < 2 || requestedChanges > 0 || commented > 0 ){
@collisdigital All changes made as per request 👍

2017-07-27 13:05 UTC, collisdigital approved these changes

2017-07-27 13:05 UTC, collisdigital commented
Please squash then this can merge

2017-07-27 14:19 UTC, merged